<?php
/** Page view: about */
?>
    <?php render_interior_hero('Qui sommes-nous ?', 'À propos', $images['hero_alt']); ?>
    <main id="main">
        <section class="section">
            <div class="container split-section split-section--about"><div class="split-section__content"><p class="eyebrow">NOTRE HISTOIRE</p><h2>Créer de la valeur par <em>l’immobilier.</em></h2><p class="lead">GELPAZ IMMO SA est une société de promotion et de vente immobilière officiellement créée en 2009, faisant suite à l’agence immobilière GELPAZ SARL qui existait depuis 1987.</p><p>Née de la volonté de garantir à chaque Burkinabè un logement décent, notre entreprise place l’humain, l’écoute et la qualité au cœur de son action. Notre connaissance du terrain nous permet d’accompagner chaque client avec justesse.</p><a class="button button--dark" href="<?= page_url('contact') ?>">Échanger avec nous <?= icon('arrow-up-right') ?></a></div><div class="split-section__media media-frame"><?php render_image($images['villa'], 'Projet immobilier Gelpaz', '(max-width: 900px) 92vw, 540px'); ?><div class="experience-badge"><strong>30<sup>+</sup></strong><span>années<br>d’expérience</span></div></div></div>
            <div class="container stats-banner"><div><strong>1987</strong><span>Les débuts de GELPAZ</span></div><div><strong>2009</strong><span>Création de GELPAZ IMMO SA</span></div><div><strong>100%</strong><span>Engagement à vos côtés</span></div><div><strong>BF</strong><span>Une expertise locale</span></div></div>
        </section>
        <section class="section section--soft"><div class="container values-layout"><div><p class="eyebrow">NOS VALEURS</p><h2>Guidés par la confiance<br>et <em>l’excellence.</em></h2></div><div class="value-list"><article><span>01</span><div><h3>Écoute active</h3><p>Comprendre vos attentes avant de vous proposer une solution.</p></div></article><article><span>02</span><div><h3>Intégrité</h3><p>Vous accompagner avec transparence à chaque décision.</p></div></article><article><span>03</span><div><h3>Professionnalisme</h3><p>Mettre notre expérience au service de la réussite de votre projet.</p></div></article><article><span>04</span><div><h3>Innovation</h3><p>Faire évoluer l’expérience immobilière pour la rendre plus simple.</p></div></article></div></div></section>
        <section class="section"><div class="container"><div class="section-heading section-heading--center"><p class="eyebrow">NOTRE ÉQUIPE</p><h2>Des experts derrière chaque <em>projet.</em></h2></div><div class="team-grid team-grid--large"><?php foreach ($team as $member) { ?><?php render_team_card($member); ?><?php } ?></div></div></section>
        <?php render_cta_band('Faisons grandir votre projet immobilier.', 'Dites-nous ce qui compte pour vous et construisons la suite ensemble.'); ?>
    </main>
