<?php
/** Page view: contact */
?>
    <?php render_interior_hero('Nous contacter', 'Contacts', $images['villa']); ?>
    <main id="main"><section class="section contact-page"><div class="container contact-layout"><div class="contact-form-wrap"><p class="eyebrow">PARLONS DE VOTRE PROJET</p><h2>Connectons-nous<br>à votre <em>avenir.</em></h2><p class="lead">Utilisez le formulaire ci-dessous ou contactez-nous directement par téléphone ou WhatsApp. Notre équipe vous répond avec plaisir.</p>
<?php if ($contact_state === 'success'): ?>
    <div class="form-success" role="status"><b><?= icon('check') ?> Message envoyé.</b><p>Merci ! Votre demande est bien arrivée chez GELPAZ IMMO. Un conseiller vous recontacte rapidement, du lundi au vendredi (<?= e($site['hours']) ?>).</p><p>Besoin d’une réponse immédiate ? <a class="text-link" href="<?= e(whatsapp_link('Bonjour GELPAZ IMMO, je viens d’envoyer un message depuis votre site.')) ?>" target="_blank" rel="noopener">Écrivez-nous sur WhatsApp <?= icon('whatsapp') ?></a></p></div>
<?php else: ?>
<?php if ($contact_state === 'error'): ?>
    <p class="form-error" role="alert"><b>L’envoi n’a pas abouti.</b> Vérifiez les champs signalés ci-dessous, ou contactez-nous directement par téléphone / WhatsApp — nous vous répondons avec plaisir.</p>
<?php endif; ?>
    <form class="contact-form" action="<?= page_url('contact') ?>#formulaire" method="post" id="formulaire" novalidate><div class="form-grid"><label>Prénom<input type="text" name="first_name" autocomplete="given-name" placeholder="Votre prénom" value="<?= e($contact_values['first_name']) ?>"></label><label>Nom<input type="text" name="last_name" autocomplete="family-name" placeholder="Votre nom" value="<?= e($contact_values['last_name']) ?>"></label><label>E-mail *<input type="email" name="email" autocomplete="email" placeholder="vous@exemple.com" value="<?= e($contact_values['email']) ?>" required aria-invalid="<?= $contact_state === 'error' && ($contact_values['email'] === '' || !filter_var($contact_values['email'], FILTER_VALIDATE_EMAIL)) ? 'true' : 'false' ?>"></label><label>Téléphone<input type="tel" name="phone" autocomplete="tel" placeholder="+226 ..." value="<?= e($contact_values['phone']) ?>"></label></div><label>Votre message *<textarea name="message" rows="5" placeholder="Parlez-nous de votre projet..." required aria-invalid="<?= $contact_state === 'error' && $contact_values['message'] === '' ? 'true' : 'false' ?>"><?= e($contact_values['message']) ?></textarea></label><label class="checkbox-label"><input type="checkbox" name="consent" value="yes" required> <span>J’accepte que GELPAZ IMMO utilise mes informations pour me recontacter, conformément à la <a href="<?= page_url('legal', ['section' => 'confidentialite']) ?>">politique de confidentialité</a>.</span></label><div class="hp-field" aria-hidden="true"><label>Site web<input type="text" name="website" tabindex="-1" autocomplete="off"></label></div><button class="button button--dark" type="submit">Envoyer le message <?= icon('arrow-up-right') ?></button><p class="form-note">Vos informations restent confidentielles et servent uniquement à vous répondre.</p></form>
<?php endif; ?>
</div><div class="contact-aside"><div class="contact-aside__visual"><?php render_image($images['hero_alt'], 'Projet immobilier', '(max-width: 900px) 92vw, 430px'); ?><div><span>GELPAZ IMMO</span><strong>La différence.</strong></div></div><div class="contact-cards"><a href="tel:+22625371055"><span><?= icon('phone') ?></span><div><small>Téléphone</small><strong><?= e($site['phone']) ?></strong></div></a><a href="<?= e(whatsapp_link('Bonjour GELPAZ IMMO, j’aimerais échanger sur mon projet immobilier.')) ?>" target="_blank" rel="noopener"><span><?= icon('whatsapp') ?></span><div><small>WhatsApp</small><strong><?= e($site['whatsapp']) ?></strong></div></a><a href="mailto:<?= e($site['email']) ?>"><span><?= icon('mail') ?></span><div><small>E-mail</small><strong><?= e($site['email']) ?></strong></div></a></div><div class="contact-hours"><p class="eyebrow">HORAIRES</p><p><b>Lundi – Vendredi</b><br><?= e($site['hours']) ?></p><p><b>Visite sur rendez-vous</b><br>Par téléphone ou WhatsApp</p></div></div></div></section><section class="map-section"><div class="map-embed map-placeholder--large"><iframe src="<?= e(map_embed_url()) ?>" title="Carte — GELPAZ IMMO, <?= e($site['address']) ?>" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe><div class="map-embed__card"><span class="map-embed__pin"><?= icon('map-pin') ?></span><div><b>GELPAZ IMMO</b><small><?= e($site['address']) ?></small><a href="<?= e(map_link_url()) ?>" target="_blank" rel="noopener">Ouvrir la carte <?= icon('arrow-up-right') ?></a></div></div></div></section><section class="section"><div class="container"><?php render_section_heading('BESOIN D’AIDE ?', 'Les réponses aux questions <em>fréquentes.</em>', '', 'center'); ?><?php render_faqs($faqs, true); ?></div></section></main>
