<?php
/** Page view: post */
$post = $selected_post ?? $posts[0];
$related = array_values(array_filter($posts, static fn (array $item): bool => ($item['slug'] ?? '') !== ($post['slug'] ?? '')));
?>
    <section class="post-hero"><?php render_header(true); ?><div class="container"><p class="eyebrow eyebrow--light">ACTUALITÉS · IMMOBILIER AU BURKINA FASO</p><h1><?= e($post['title']) ?></h1><div class="post-meta">Par GELPAZ IMMO <span>·</span> <time datetime="<?= e($post['iso'] ?? '') ?>"><?= e($post['date']) ?></time> <span>·</span> Actualité</div></div></section>
    <main id="main"><section class="section single-post"><div class="container single-post__layout"><article><?php render_image($post['image'], $post['title'], '(max-width: 760px) 92vw, 720px', 'single-post__image', false, 835, 467); ?><p class="eyebrow">L’ESSENTIEL</p><p class="lead"><?= e($post['excerpt']) ?></p>
<?php foreach (($post['content'] ?? []) as $block): ?>
    <h2><?= e($block['h']) ?></h2><p><?= e($block['p']) ?></p>
<?php endforeach; ?>
    <div class="post-share"><span>Tags : immobilier · investissement · habitat</span><span class="share-links">Partager : <a href="https://wa.me/?text=<?= rawurlencode($post['title'] . ' · GELPAZ IMMO') ?>" target="_blank" rel="noopener" aria-label="Partager sur WhatsApp"><?= icon('whatsapp') ?></a><a href="mailto:?subject=<?= rawurlencode($post['title']) ?>&body=<?= rawurlencode('À lire sur le site GELPAZ IMMO : ' . $post['title']) ?>" aria-label="Partager par e-mail"><?= icon('mail') ?></a></span></div></article><aside class="blog-sidebar"><div class="sidebar-card"><p class="eyebrow">ARTICLES RÉCENTS</p><?php foreach (array_slice($related, 0, 4) as $item): ?><a class="recent-post" href="<?= e(page_url('post', ['slug' => $item['slug']])) ?>"><?php render_image($item['image'], '', '60px', '', true, 525, 328); ?><span><?= e($item['title']) ?><small><time datetime="<?= e($item['iso'] ?? '') ?>"><?= e($item['date']) ?></time></small></span></a><?php endforeach; ?></div><div class="sidebar-card sidebar-card--cta"><p class="eyebrow">UN PROJET ?</p><h3>Parlons-en dès maintenant.</h3><p>Un conseiller vous répond par téléphone ou WhatsApp.</p><a class="button button--dark button--full" href="<?= page_url('contact') ?>">Nous contacter <?= icon('arrow-up-right') ?></a></div></aside></div></section><section class="section section--soft"><div class="container"><?php render_section_heading('À LIRE AUSSI', 'Poursuivez votre <em>lecture.</em>', '', 'left'); ?><div class="blog-grid blog-grid--three"><?php foreach (array_slice($related, 0, 3) as $item) { render_blog_card($item); } ?></div></div></section></main>
