<?php
/** Page view: property */
?>
    <?php render_interior_hero($selected_property['title'], 'Détails de la propriété', $selected_property['image']); ?>
    <main id="main">
        <section class="section property-detail"><div class="container property-detail__layout"><aside class="property-summary"><p class="eyebrow">FICHE PROPRIÉTÉ</p><h2><?= e($selected_property['title']) ?></h2><p class="property-summary__location"><?= icon('map-pin') ?> <?= e($selected_property['location']) ?></p><div class="summary-price"><span><?= e($selected_property['category']) ?></span><strong><?= e($selected_property['price']) ?></strong></div><div class="summary-list"><div><span>Modèle</span><b><?= e($selected_property['model']) ?></b></div><div><span>Surface bâtie</span><b><?= e($selected_property['area']) ?></b></div><div><span>Chambres</span><b><?= e($selected_property['beds']) ?></b></div><div><span>Salles d’eau</span><b><?= e($selected_property['baths']) ?></b></div></div><a class="button button--dark button--full" href="<?= page_url('contact') ?>">Contacter GELPAZ IMMO <?= icon('arrow-up-right') ?></a></aside><?php $gallery = $selected_property['gallery'] ?? array_slice($images, 0, 1); ?>
<div class="property-detail__main"><div class="property-gallery" data-gallery><button class="property-gallery__zoom" type="button" data-lightbox-open aria-label="Agrandir la photo principale"><?php render_image($gallery[0], $selected_property['title'], '(max-width: 900px) 92vw, 660px', 'property-gallery__main', false); ?></button><div class="property-gallery__thumbs">
<?php foreach ($gallery as $index => $photo): ?>
    <button type="button" data-lightbox-open data-photo="<?= e($photo) ?>" aria-label="Voir la photo <?= $index + 1 ?> en grand"<?= $index === 0 ? ' aria-current="true"' : '' ?>><?php render_image($photo, 'Vue du projet — ' . $selected_property['title'] . ' (photo ' . ($index + 1) . ')', '160px', '', true, 835, 467); ?></button>
<?php endforeach; ?>
</div></div><div class="property-copy"><p class="eyebrow">DESCRIPTION</p><h2>Un lieu pensé pour <em>bien vivre.</em></h2><p><?= e($selected_property['description']) ?> Profitez d’un cadre harmonieux, de volumes généreux et d’un accompagnement GELPAZ IMMO à chaque étape.</p><div class="amenities"><span class="amenity"><?= icon('home') ?> Espace familial</span><span class="amenity"><?= icon('shield') ?> Cadre sécurisé</span><span class="amenity"><?= icon('tool') ?> Finitions soignées</span><span class="amenity"><?= icon('heart') ?> Confort durable</span></div></div><div class="location-block"><p class="eyebrow">LOCALISATION</p><h3>Votre propriété au cœur de Ouagadougou</h3><div class="map-embed"><iframe src="<?= e(map_embed_url()) ?>" title="Carte — <?= e($selected_property['location']) ?>" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe><div class="map-embed__card"><span class="map-embed__pin"><?= icon('map-pin') ?></span><div><b><?= e($selected_property['location']) ?></b><small><?= e($site['address']) ?></small><a href="<?= e(map_link_url()) ?>" target="_blank" rel="noopener">Itinéraire <?= icon('arrow-up-right') ?></a></div></div></div></div></div></div></section><section class="section related-section"><div class="container"><?php render_section_heading('AUTRES PROPRIÉTÉS', 'Découvrez aussi nos <em>opportunités.</em>', '', 'center'); ?><div class="property-grid property-grid--three"><?php foreach (array_slice($properties, 1, 3) as $property) { render_property_card($property, true); } ?></div></div></section>
    </main>
