<?php
/** Page view: services */
?>
    <?php render_interior_hero('Nos activités', 'Nos activités', $images['hero']); ?>
    <main>
        <section class="section"><div class="container"><?php render_section_heading('NOTRE SAVOIR-FAIRE', 'Des solutions immobilières <em>complètes.</em>', 'Une approche globale, pensée pour répondre aux réalités de chaque projet.', 'center'); ?><div class="service-cards service-cards--large"><?php foreach ($services as $service): ?><article class="service-card"><span class="service-card__icon"><?= e($service['icon']) ?></span><h3><?= e($service['title']) ?></h3><p><?= e($service['text']) ?></p><a class="text-link text-link--dark" href="<?= page_url('contact') ?>">En savoir plus <span>↗</span></a></article><?php endforeach; ?></div></div></section>
        <section class="section section--soft"><div class="container process-feature process-feature--services"><div class="process-feature__image"><img src="<?= img_url($images['villa']) ?>" alt="Accompagnement immobilier" loading="lazy"></div><div class="process-feature__content"><p class="eyebrow">NOTRE PROCESSUS</p><h2>Des étapes simples vers le <em>succès.</em></h2><p>Parce qu’un projet immobilier mérite de la clarté, nous vous guidons du premier échange jusqu’à la concrétisation.</p><a class="button button--dark" href="<?= page_url('contact') ?>">Prendre rendez-vous <span>↗</span></a></div></div><div class="container steps-row steps-row--cards"><div><span>01</span><h3>Premier échange</h3><p>Nous découvrons votre besoin, vos envies et votre budget.</p></div><div><span>02</span><h3>Choix du bien</h3><p>Nous vous présentons les opportunités qui vous correspondent.</p></div><div><span>03</span><h3>Accompagnement</h3><p>Nous restons présents et disponibles pour répondre à toutes vos questions.</p></div><div><span>04</span><h3>Finalisation</h3><p>Votre projet se concrétise dans un climat de confiance.</p></div></div></section>
        <?php render_cta_band(); ?>
    </main>
